// packages/reader-react/src/Reader.tsx
// Thin React shell over `ReaderController`: owns the host element, mount/destroy,
// and the effect forwarding settings changes.

import type { Book, Section } from "@lostcoords/lumi-epub";
import type { ReaderExtension, ReaderStore, SettingsPort } from "@lostcoords/lumi-reader-core";
import { useEffect, useRef } from "react";
import { ReaderController } from "./controller";

export type ReaderProps = {
  store: ReaderStore;
  settings: SettingsPort;
  /** Bump on any settings change to trigger the forwarding effect (React can't auto-track `settings.get()`). */
  settingsVersion?: unknown;
  extensions?: ReaderExtension[];
  spreadPartnerFor?: (section: Section, book: Book) => Section | null;
  className?: string;
};

// Props are captured once at mount. Remount via `<Reader key={bookId} … />` to reset the engine.
export function Reader(props: ReaderProps): React.JSX.Element {
  const hostRef = useRef<HTMLDivElement>(null);
  const controllerRef = useRef<ReaderController>(null);

  // Latest props for the once-only mount effect, without re-subscribing it.
  const propsRef = useRef(props);
  propsRef.current = props;

  useEffect(() => {
    const host = hostRef.current;
    if (!host) return;
    const p = propsRef.current;
    const controller = new ReaderController({
      store: p.store,
      settings: p.settings,
      extensions: p.extensions,
      spreadPartnerFor: p.spreadPartnerFor,
    });
    controller.mount(host);
    controllerRef.current = controller;
    return () => {
      controller.destroy();
      controllerRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Inert until the first render lands (controller guards it).
  useEffect(() => {
    controllerRef.current?.applySettings(props.settings.get());
  }, [props.settings, props.settingsVersion]);

  return (
    <div
      ref={hostRef}
      className={props.className}
      data-lumi-reader
      style={{ position: "relative", width: "100%", height: "100%" }}
    />
  );
}

// packages/reader-svelte/src/Reader.svelte
// Thin Svelte 5 shell over `ReaderController`. All orchestration lives in the
// framework-agnostic controller; this component owns the host element, the
// mount/destroy lifecycle, and the reactive effect that forwards settings changes.

import type { Book, Section } from "@lostcoords/lumi-epub";
import type { ReaderExtension, ReaderStore, SettingsPort } from "@lostcoords/lumi-reader-core";
import { onMount } from "svelte";
import { ReaderController } from "./controller";

type Props = {
  store: ReaderStore;
  settings: SettingsPort;
  extensions?: ReaderExtension[];
  spreadPartnerFor?: (section: Section, book: Book) => Section | null;
  class?: string;
};

// All props are captured once at mount. `store` content changes flow in through the controller's own
// subscription; `settings` changes flow through the effect below. To reset the engine against a
// different store/settings, remount the component (`{#key store}<Reader ... />{/key}`) — this
// deliberately does NOT tear down and rebuild on prop-identity churn (e.g. an inline `extensions`
// array), which an `$effect` here would.
let { store, settings, extensions, spreadPartnerFor, class: className }: Props = $props();

let host: HTMLDivElement | undefined = $state();
let controller: ReaderController | undefined;

onMount(() => {
  if (!host) return;
  const c = new ReaderController({ store, settings, extensions, spreadPartnerFor });
  c.mount(host);
  controller = c;
  return () => {
    c.destroy();
    controller = undefined;
  };
});

// `settings.get()` reads the app's reactive preferences, so this effect re-runs on any settings change and the controller diffs the snapshot. Read it unconditionally (not behind `controller?`) so the reactive dependency is always registered — optional chaining would skip the call on the first run before mount.
$effect(() => {
  const snapshot = settings.get();
  controller?.applySettings(snapshot);
});
</script>

<div bind:this={host} class={className} data-lumi-reader style="position:relative;width:100%;height:100%"></div>
